name: notiondb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  envied: ^0.5.3
  flutter:
    sdk: flutter
  notion_api: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  envied_generator: ^0.5.3
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
